### ISSUE TITLE
Overlapping CSS styles

### ISSUE THREAD

**Issue by mike2003** [mgmeyers/obsidian-embedded-note-titles#10]
I used styles for CSS customization.
.embedded-note-titles .markdown-preview-view > h1,
.embedded-note-titles .CodeMirror-scroll > h1 {
...}
But it also works in the Community plugins Browser in the plugins description.
Can this be avoided somehow?

**Comment by mgmeyers** [comment]
If you replace `.markdown-preview-view` with `.markdown-preview-view:not(.community-plugin-readme)` it should do the trick.

**Comment by mike2003** [comment]
Yes, thanks it works.
