### ISSUE TITLE
FR: Get title from metadata

### ISSUE THREAD

**Issue by verazorita** [mgmeyers/obsidian-embedded-note-titles#13]
Could it be possible for the plugin to offer the possibility of getting the title not from the filename but from the declared metadata?

Thank you!

**Comment by mgmeyers** [comment]
Hi @veradrawer. There is now a setting to accomplish this. Let me know if you have any issues with it.

**Comment by verazorita** [comment]
Thank you so much! I've tried to update the plugin to test this, but I can't get to do it.

[Link to issue](https://github.com/mgmeyers/obsidian-embedded-note-titles/issues/18)
