### ISSUE TITLE
Feature request: Disable when note begins with a title or based on frontmatter

### ISSUE THREAD

**Issue by sheeley** [mgmeyers/obsidian-embedded-note-titles#14]
This plugin is delightful for notes where I do not have a title - some of my legacy notes already have a title, though, and sometimes I want to explicitly override the title.

I'd suggest that:
* If a note's text content starts with a title, disable
* If a note's frontmatter contains `embeddedTitle: false`, disable

For example:
```
---
embeddedTitle: false
foo: bar
---

# Title that Overrides Automatically Generated Title
Foo bar baz booze.
```

If interested, I'd be happy to take a look at implementing.

**Comment by mgmeyers** [comment]
This is now possible in the latest version. This requires obsidian 0.13.8, which is currently an insider's release.

<img width="893" alt="Screen Shot 2021-12-13 at 1 08 51 PM" src="https://user-images.githubusercontent.com/2694747/145889082-1a0570fc-79f1-4a79-b277-f8a0ab300630.png">

**Comment by mgmeyers** [comment]
Obsidian 0.13.14 has been released to the public, and this feature is now publicly available.
