### ISSUE TITLE
Not working with Live Preview on v0.13.12

### ISSUE THREAD

**Issue by DryIce1** [mgmeyers/obsidian-embedded-note-titles#16]
**What**
- Not working when Live Preview is **enabled**
- If Live Preview is then **disabled**, the embedded note titles work again.

I look forward to this being updated, 
Thanks!

**Comment by sammosna** [comment]
+1 same issue

**Comment by dcoales** [comment]
I've submitted a pull request which adds a couple of changes to support Live Preview.

**Comment by mgmeyers** [comment]
Live preview is now supported in the latest version
