### ISSUE TITLE
[BUG] Can't enable plugin v. 1.1.2 in Obsidian 

### ISSUE THREAD

**Issue by verazorita** [mgmeyers/obsidian-embedded-note-titles#18]
Writing it down here because I don't know if this is a bug with Obsidian or with the plugin.
After downloading it from the Obsidian community plugin client (v0.12.19 / Installer v0.10.7), the installed version is the 1.0.2:

![imagen](https://user-images.githubusercontent.com/75331117/145860391-33a3db83-16f4-4f78-b784-f57bbf055f5f.png)

Obsidian tells me there is no available update, yet by checking the plugin on the tab informs me it is. Clicking on update renders a "succesfully updated" that does nothing:

![imagen](https://user-images.githubusercontent.com/75331117/145860182-b0e171f6-0d67-43f7-90ca-8e6192e14c3d.png)

I decide to manually install it via BRAT, and I get an incompatibility issue.
![imagen](https://user-images.githubusercontent.com/75331117/145860799-be644c51-d42e-4061-b921-0a5cb4d5a91f.png)
![imagen](https://user-images.githubusercontent.com/75331117/145860822-e22eaaf5-d3bf-4d9b-9a99-72f0ff18f907.png)

**Comment by mgmeyers** [comment]
@veradrawer This isn't a bug, rather 1.1.2 only works on obsidian 0.13.8 and greater—which is currently only available to insiders. Once live preview is released to the public, this plugin will be available to all

**Comment by mgmeyers** [comment]
@veradrawer Now that obsidian 0.13.14 has been released, you should be able to install this plugin.
