### ISSUE TITLE
Setting to hide Title not working

### ISSUE THREAD

**Issue by edward-peters** [mgmeyers/obsidian-embedded-note-titles#19]
Thank you for this terrific plugin, just what I need!
I have latest Insider Build 0.13.9 but when I turn on the setting to Hide Title when Level 1 Heading is present, that heading is not hidden.
See screenshot in Minimal theme
<img width="883" alt="Screenshot 2021-12-14 at 17 02 14" src="https://user-images.githubusercontent.com/43352605/146034368-b6e9673e-968c-4a38-923c-ff267aeba84f.png">
.

**Comment by mgmeyers** [comment]
@edward-peters Would you be willing to send me this file? This feature seems to be working ok for me, but I wonder if there's some edge case I'm missing

**Comment by edward-peters** [comment]
@mgmeyers yes absolutely. By ‘file’ do you mean the one markdown note file?

**Comment by mgmeyers** [comment]
@edward-peters Yes exactly.

**Comment by edward-peters** [comment]
[Fugue.md](https://github.com/mgmeyers/obsidian-embedded-note-titles/files/7729964/Fugue.md)
Sorry for the delay, here it is.

**Comment by mgmeyers** [comment]
Hmm, strange @edward-peters , the title seems to be correctly hidden for me:


<img width="585" alt="Screen Shot 2021-12-16 at 12 51 04 PM" src="https://user-images.githubusercontent.com/2694747/146447201-42428c27-5672-4c3f-9872-29d6fbd01ff4.png">

<img width="582" alt="Screen Shot 2021-12-16 at 12 54 45 PM" src="https://user-images.githubusercontent.com/2694747/146447629-c2db2157-9073-493e-a849-daa453bdab6f.png">


Here are my settings:

<img width="740" alt="Screen Shot 2021-12-16 at 12 53 13 PM" src="https://user-images.githubusercontent.com/2694747/146447426-3127c038-7344-40bb-b9aa-9a2bad7f577a.png">

This this issue occur both in edit and preview modes?

**Comment by edward-peters** [comment]
Thanks so much @mgmeyers. The issue was that I did not have any value in the first setting field. When I added 'title' there like you have it, it worked. I assumed the settings were independent from each other (I don't use front matter).
Perhaps you could add a line of description explaining that the first setting must not be empty if one wants the second to work?
