### ISSUE TITLE
H1 styling from theme

### ISSUE THREAD

**Issue by Ampa** [mgmeyers/obsidian-embedded-note-titles#2]
Thanks for the handy plugin.

The inserted H1 is not themed, based on the theme selected in Settings > Appearance.

Is this a deliberate choice? 
Would it be possible to add the CSS classes to use the theme styling?

**Comment by mgmeyers** [comment]
@Ampa The styling for embedded titles can now be adjusted using the Style Settings plugin. Themes can go about styling h1 tags in many different ways, though, and may not style embedded headings directly. I would open an issue with the theme author if this is the case.
