### ISSUE TITLE
The heading in line 1 gets two collapse arrows in Live Preview mode

### ISSUE THREAD

**Issue by Signynt** [mgmeyers/obsidian-embedded-note-titles#20]
### Steps to Reproduce

1. Enable plugin
2. Use Live Preview mode
3. Turn on "Fold Heading" in the Editor settings pane
4. Write a title in the very first line of a note (which heading size does not matter, it just must be in line 1)

#### Result
![image](https://user-images.githubusercontent.com/67801159/146154439-4d268f7c-c4a6-4122-b9a6-2071b602fb2f.png)
The heading will have two arrows for collapsing it.

#### Expected Result
![image](https://user-images.githubusercontent.com/67801159/146154570-1294df2e-7703-49f9-b5df-7f521b03aa8c.png)
The heading should only have one arrow for collapsing it.

### Details
- Embedded Note Titles Version: 1.1.6
- Obsidian Version: v0.13.10
- OS: MacOS 12.1

**Comment by mgmeyers** [comment]
@Signynt This should be fixed now. Let me know if you still have issues
