### ISSUE TITLE
[Bug] Can't insert caret in last 2 lines of document.

### ISSUE THREAD

**Issue by Ampa** [mgmeyers/obsidian-embedded-note-titles#23]
Once the caret leaves the last 2 lines of my markdown document, I can no longer click to insert the caret in these final two lines, nor use the cursor keys to move the caret into these lines.

If I disable the plugin, then normal behaviour resumes.

![Obsidian Embed H1](https://user-images.githubusercontent.com/1459388/146941058-b70e88d0-cfdb-4afa-a6ea-7bbc264b4423.gif)

**Comment by mgmeyers** [comment]
@Ampa This should be fixed now. Let me know if you still have issues with it.

**Comment by Ampa** [comment]
Awesome! Seems to be fixed for me.

Thank you.
