### ISSUE TITLE
Daily note title format not applied

### ISSUE THREAD

**Issue by dcoales** [mgmeyers/obsidian-embedded-note-titles#24]
Hi,

I'm using version 1.2.2 and have entered the following as my daily note title format but it's not being applied.

ddd, Do MMMM YYYY

I have changed the format of my daily note file titles to the format below if perhaps that is causing the problem.

YYYY_MM_DD

**Comment by mgmeyers** [comment]
@dcoales You mentioned changing the titles of your daily notes, did you also change the format in daily note settings? This is what's used to parse the dates.

<img width="886" alt="Screen Shot 2021-12-26 at 9 45 07 AM" src="https://user-images.githubusercontent.com/2694747/147416028-8dfce12a-1f20-4488-a3f0-bdf8301da3c4.png">

<img width="577" alt="Screen Shot 2021-12-26 at 9 45 45 AM" src="https://user-images.githubusercontent.com/2694747/147416044-5e829b24-5f90-45dc-b04a-5888dfe031e3.png">

**Comment by dcoales** [comment]
My settings are 

![image](https://user-images.githubusercontent.com/19651447/147467973-b5eeaf0b-1838-432d-8550-8cd7cd50a284.png)

But my daily notes file looks like:

![image](https://user-images.githubusercontent.com/19651447/147468084-0126b089-6d6c-402c-ba34-3c6850972424.png)

And my settings are 
![image](https://user-images.githubusercontent.com/19651447/147468185-099141a6-78db-480c-ad1a-7801f43f334e.png)

For version 1.2.3
![image](https://user-images.githubusercontent.com/19651447/147468244-5572f8b8-1287-457a-933d-287ad96a5a16.png)

I'll see if I can debug the code to see what's going on.

**Comment by dcoales** [comment]
Okay, totally failed to find the source in the developer options sources tab.

**Comment by mgmeyers** [comment]
Ok, this should be fixed now @dcoales Let me know if you have any more trouble with it.

**Comment by dcoales** [comment]
That did the trick.  Thanks very much.
