### ISSUE TITLE
Ability to center justify embedded titles

### ISSUE THREAD

**Issue by insecurejezza** [mgmeyers/obsidian-embedded-note-titles#26]
Would be great to have the option to center justify or other options. Either throughStyle Settings or through a CSS snippet.

Thanks for the plugin!

**Comment by seangaffney** [comment]
You can do this through existing functionality in Obsidian. Simply create a new CSS file in the `/.obsidian/snippets/` folder in your vault called `embedded-note-titles.css` (or similar) and add the the CSS rules you'd like, for example:

```css
.embedded-note-titles h1 {
  text-align: center;
}
```

Then in Obsidian's Appearance settings, scroll down to the CSS snippets section and turn them on.

Hope that helps!

**Comment by mgmeyers** [comment]
Thanks for the snippet @seangaffney. As a slight modification, I would do something like:

```
h1.embedded-note-title {
  text-align: center;
}
```
