### ISSUE TITLE
Options to hide embedded title do not work

### ISSUE THREAD

**Issue by seangaffney** [mgmeyers/obsidian-embedded-note-titles#27]
I've tried adding an H1 and also using the `embedded-title: false` setting in the frontmatter, but the embedded title never gets the `embedded-note-title__hidden` class added to it. I briefly looked through the code and couldn't find anything obvious. Can you replicate?

Obsidian version 0.13.19
Plugin version 1.2.6

PS - This plugin scratches a serious itch for me, thank you for creating it!

**Comment by seangaffney** [comment]
I just saw in #19 that you need to have a value in the `Frontmatter field as title` setting in order for the two "hide" functions to work. I agree with @edward-peters that this is not intuitive. Is there a technical reason for this requirement?

**Comment by mgmeyers** [comment]
@seangaffney Thanks for reporting this, and no, no technical reason. This is a bug and should work regardless of the `title` field being set.

**Comment by cesar-programs** [comment]
I look forward to this bug being resolved

* Scratch that, I found the issue as noted above. Thank you for the plug-in

https://github.com/mgmeyers/obsidian-embedded-note-titles/issues/19#issuecomment-996790800
