### ISSUE TITLE
Titles are too big. Could we get a setting to change the heading? I'd prefer just H3 at the top since I use multipane layouts often.

### ISSUE THREAD

**Issue by classicrob** [mgmeyers/obsidian-embedded-note-titles#3]

**Comment by yutaizhou** [comment]
Hi @classicrob, the following worked for me, just put it in a .css snippet and have Obsidian use it. Feel free to replace font-size, weight, etc, with whatever you need:

```
.embedded-note-titles .markdown-preview-view > h1, /* ...preview mode styles... */
.embedded-note-titles .is-readable-line-width.markdown-preview-view > h1, /* ...preview mode styles with readable line width enabled... */
.embedded-note-titles .CodeMirror-scroll > h1, /* ...edit mode styles... */
.embedded-note-titles .is-readable-line-width .CodeMirror-scroll > h1 /* ...edit mode styles with readable line width enabled... */
{
font-size: 22px !important;
}
```

**Comment by classicrob** [comment]
Thank you!

**Comment by dricard** [comment]
That doesn't work for at all.

**Comment by mgmeyers** [comment]
In the latest insider release, there are style settings (via the Style Settings plugin) to control the styling of the title. This will be available more widely once live preview is released to the public.

**Comment by mgmeyers** [comment]
Obsidian 0.13.14 has been released to the public, and the styling of headings can be adjusted via Style Settings
