### ISSUE TITLE
Error when file opened in New Window

### ISSUE THREAD

**Issue by Sriramgireesh** [mgmeyers/obsidian-embedded-note-titles#37]
After the 15.6 update, individual notes can be opened in new window. However, when the file is opened in a new window, the title of the note is displayed 4 times. When the live preview/read modes are toggled, the no of titles increases at every such instance.
![image](https://user-images.githubusercontent.com/66196487/179160344-a9cb5497-302b-4de7-9bd5-f9cf0b0d9da9.png)

**Comment by mgmeyers** [comment]
Thanks @Sriramgireesh, this should be fixed
