### ISSUE TITLE
Bug: all pages show the same title when use other languages.

### ISSUE THREAD

**Issue by lokiter** [mgmeyers/obsidian-embedded-note-titles#5]
When I use some Japanese or Chinese words in the title, the preview will show the same title if I click another page.
For example :
I named two pages, one is "の" and another is "い".
When I click the first page, the title will show "の". Now If I click  the  "い" page , it still show "の" but not "い".

Thank you for bringing such a great plugin and looking forward to your reply!

**Comment by yo-goto** [comment]
the same problem occurs sometimes.
![titleremain](https://user-images.githubusercontent.com/50942816/118501690-f3829a00-b763-11eb-8520-98a0d534e94d.gif)

**Comment by mgmeyers** [comment]
Thanks @lokiter and @yo-goto! This should be fixed now. Try updating the plugin, and let me know if you still have issues.

**Comment by lokiter** [comment]
@mgmeyers  It works great now, thank you!
