### ISSUE TITLE
[Bug] Panes adjacent to the current note flicker changing Edit and preview mode

### ISSUE THREAD

**Issue by yo-goto** [mgmeyers/obsidian-embedded-note-titles#6]
panes flicker when I change edit & preview mode.
![pane flicker](https://user-images.githubusercontent.com/50942816/119159350-17125100-ba92-11eb-99f6-dac8c4e453d7.gif)

**Comment by mgmeyers** [comment]
@yo-goto This is fixed in the latest version of the plugin. This version requires the latest insider build, but will be publicly available once live preview is.

**Comment by mgmeyers** [comment]
Obsidian 0.13.14 has been released to the public, and this should no longer be an issue
