### ISSUE TITLE
Convert Journal File Names to different Date Style

### ISSUE THREAD

**Issue by dcoales** [mgmeyers/obsidian-embedded-note-titles#8]
For compatibility with LogSeq I use the YYYY-MM-DD file name style for journal files but I would prefer the title added to the file to be in  more readable format e.g. Saturday, 17th July 2021.  Would it be possible to have a date format setting and have the title for any file from the daily notes folder converted to the preferred format ?

**Comment by mgmeyers** [comment]
@dcoales This is now possible in the latest version. It requires the most recent obsidian insiders build, though.

**Comment by mgmeyers** [comment]
Obsidian 0.13.14 has been released to the public, and this feature is now publicly available.
